library(shiny)
library(plotly)
library(tidyverse)

# load the data
setwd("/Users/anhbach/Desktop/DS2003")
movies <- read_csv("IMDB TMDB Movie Metadata Big Dataset (1M).csv", show_col_types = FALSE)

# pull all unique genres from the genres_list column
all_genres <- movies$genres_list %>%
  str_extract_all("'([^']+)'") %>%
  unlist() %>%
  str_remove_all("'") %>%
  unique() %>%
  sort()

# take the first genre listed for each movie
movies$primary_genre <- str_extract(movies$genres_list, "(?<=')[^']+(?=')")

# make release year numeric
movies$release_year <- as.numeric(movies$release_year)

# clean revenue and budget
movies$revenue[movies$revenue < 0] <- NA
movies$budget[movies$budget < 0] <- NA

# create a decade label like "1990s", "2000s"
movies$decade <- paste0(floor(movies$release_year / 10) * 10, "s")

# uniform color palette for genres across all plots
genre_colors <- c(
  "Action"          = "#E74C3C",
  "Adventure"       = "#E67E22",
  "Animation"       = "#F1C40F",
  "Comedy"          = "#2ECC71",
  "Crime"           = "#1ABC9C",
  "Documentary"     = "#3498DB",
  "Drama"           = "#2980B9",
  "Family"          = "#9B59B6",
  "Fantasy"         = "#8E44AD",
  "History"         = "#D35400",
  "Horror"          = "#C0392B",
  "Music"           = "#16A085",
  "Mystery"         = "#2C3E50",
  "Romance"         = "#E91E63",
  "Science Fiction"  = "#00BCD4",
  "Thriller"        = "#607D8B",
  "TV Movie"        = "#795548",
  "Unknown"         = "#9E9E9E",
  "War"             = "#455A64",
  "Western"         = "#BF360C"
)


ui <- fluidPage(
  
  # full browser width
  tags$head(tags$style(HTML("
    .container-fluid { max-width: 100%; padding-left: 30px; padding-right: 30px; }
  "))),
  
  titlePanel("What Determines a Movie's Success?"),
  
  tabsetPanel(
    
    # tab 1: Ratings Over Time
    tabPanel("Ratings Over Time",
             br(),
             tags$p("Explore how average audience ratings have changed over time across genres."),
             fluidRow(
               column(6,
                      selectInput("genre1", "Select Genre:",
                                  choices = c("All", all_genres))
               ),
               column(6,
                      sliderInput("year_range1", "Release Year Range:",
                                  min = 1970, max = 2023, value = c(1970, 2023), sep = "")
               )
             ),
             plotlyOutput("plot1", width = "100%", height = "650px"),
             tags$p(textOutput("count1"), style = "color: gray; text-align: center;")
    ),
    
    # tab 2: Director vs. Revenue
    tabPanel("Director vs. Revenue",
             br(),
             tags$p("Compare revenue generated by top-rated movies, grouped by director."),
             fluidRow(
               column(4,
                      sliderInput("year_range2", "Release Year Range:",
                                  min = 1970, max = 2023, value = c(1970, 2023), sep = "")
               ),
               column(4,
                      numericInput("top_n", "Top N Movies by Rating:",
                                   value = 10, min = 5, max = 50)
               ),
               column(4,
                      selectInput("genre2", "Filter by Genre:",
                                  choices = c("All", all_genres))
               )
             ),
             plotlyOutput("director_bar", width = "100%", height = "650px"),
             tags$p(textOutput("count2"), style = "color: gray; text-align: center;")
    ),
    
    # tab 3: Budget vs. Success
    tabPanel("Budget vs. Success",
             br(),
             tags$p("Explore whether higher budgets lead to more successful movies.
             Switch the success metric and filter by genre to find patterns."),
             fluidRow(
               column(3,
                      selectInput("metric", "Success Metric (Y-axis):",
                                  choices = c("Revenue"     = "revenue",
                                              "IMDb Rating" = "IMDB_Rating",
                                              "TMDB Rating" = "vote_average",
                                              "Metascore"   = "Meta_score"))
               ),
               column(3,
                      radioButtons("scale", "Budget Scale:",
                                   choices = c("Log", "Linear"), inline = TRUE)
               ),
               column(3,
                      selectInput("genre3", "Filter by Genre:",
                                  choices = c("All", all_genres))
               ),
               column(3,
                      sliderInput("year_range3", "Release Year Range:",
                                  min = 1970, max = 2023, value = c(1970, 2023), sep = "")
               )
             ),
             plotlyOutput("scatter", width = "100%", height = "650px"),
             tags$p(textOutput("count3"), style = "color: gray; text-align: center;")
    ),
    
    # tab 4: Audience vs. Critics
    tabPanel("Audience vs. Critics",
             br(),
             tags$p("Compare how audiences and critics rate movies across genres.
             Metascore is scaled from 0-100 down to 1-10 so both bars
             are directly comparable."),
             fluidRow(
               column(4,
                      radioButtons("rating_source", "Audience Rating:",
                                   choices = c("IMDb Rating" = "IMDB_Rating",
                                               "TMDB Rating" = "vote_average"),
                                   inline = TRUE)
               ),
               column(4,
                      sliderInput("year_range4", "Release Year Range:",
                                  min = 1970, max = 2023, value = c(1970, 2023), sep = "")
               ),
               column(4,
                      selectInput("sort_by", "Sort Genres By:",
                                  choices = c("Audience Rating"     = "audience",
                                              "Critic Score"         = "critic",
                                              "Biggest Disagreement" = "gap"))
               )
             ),
             plotlyOutput("bars", width = "100%", height = "650px"),
             tags$p(textOutput("count4"), style = "color: gray; text-align: center;")
    )
  )
)


server <- function(input, output) {
  
  # ---- TAB 1: Ratings Over Time ----
  output$plot1 <- renderPlotly({
    df <- movies
    df$release_year <- as.numeric(substr(df$release_date, 1, 4))
    df <- df[!is.na(df$vote_average), ]
    df <- df[df$release_year >= input$year_range1[1] &
               df$release_year <= input$year_range1[2], ]
    
    if (input$genre1 != "All") {
      df <- df[df$primary_genre == input$genre1, ]
    }
    
    plot_data <- df %>%
      group_by(release_year, primary_genre) %>%
      summarise(avg_rating = mean(vote_average), .groups = "drop")
    
    top_genres <- df %>%
      group_by(primary_genre) %>%
      summarise(count = n()) %>%
      arrange(desc(count)) %>%
      head(6)
    
    plot_data <- plot_data[plot_data$primary_genre %in% top_genres$primary_genre, ]
    
    # match colors to the uniform palette
    used_genres <- unique(plot_data$primary_genre)
    colors_used <- genre_colors[used_genres]
    
    plot_ly(plot_data,
            x = ~release_year, y = ~avg_rating,
            color = ~primary_genre, colors = colors_used,
            type = "scatter", mode = "lines") %>%
      layout(
        title = "Average Rating Over Time (Top Genres)",
        xaxis = list(title = "Year"),
        yaxis = list(title = "Rating"),
        legend = list(orientation = "h", y = -0.15)
      )
  })
  
  output$count1 <- renderText({
    paste("Showing ratings from", input$year_range1[1], "to", input$year_range1[2])
  })
  
  # ---- TAB 2: Director vs. Revenue ----
  get_data2 <- reactive({
    df <- movies
    df <- df[!is.na(df$release_year), ]
    df <- df[!is.na(df$vote_average) & !is.na(df$revenue), ]
    df <- df[df$revenue > 0, ]
    df <- df[!is.na(df$Director), ]
    df <- df[df$vote_count >= 10000, ]
    df <- df[df$release_year >= input$year_range2[1] &
               df$release_year <= input$year_range2[2], ]
    
    if (input$genre2 != "All") {
      df <- df[df$primary_genre == input$genre2, ]
    }
    
    df %>%
      arrange(desc(vote_average)) %>%
      slice_head(n = input$top_n)
  })
  
  output$director_bar <- renderPlotly({
    df <- get_data2()
    
    validate(
      need(nrow(df) > 0, "No movies found for this selection. Please adjust your filters.")
    )
    
    agg <- df %>%
      group_by(Director) %>%
      summarise(
        total_revenue = sum(revenue, na.rm = TRUE),
        avg_popularity = mean(popularity, na.rm = TRUE),
        rating = mean(vote_average, na.rm = TRUE),
        stars = paste(unique(c(first(Star1), first(Star2), first(Star3), first(Star4))), collapse = ", "),
        .groups = "drop"
      )
    
    agg$hover <- paste(
      "Director:", agg$Director,
      "<br>Revenue: $", format(agg$total_revenue, big.mark = ","),
      "<br>Avg Rating:", round(agg$rating, 1),
      "<br>Stars:", agg$stars
    )
    
    title_text <- if (input$genre2 == "All") {
      "Top Rated Movies: Director vs Revenue (All Genres)"
    } else {
      paste("Top Rated", input$genre2, "Movies: Director vs Revenue")
    }
    
    plot_ly(
      data = agg,
      x = ~reorder(Director, -rating),
      y = ~total_revenue,
      type = "bar",
      textposition = "none",
      marker = list(color = ~avg_popularity,
                    colorscale = list(c(0, "#3498DB"), c(1, "#E74C3C")),
                    showscale = TRUE,
                    colorbar = list(title = "Popularity")),
      text = ~hover,
      hoverinfo = "text"
    ) %>%
      layout(
        title = title_text,
        xaxis = list(title = "Director"),
        yaxis = list(title = "Total Revenue ($)")
      )
  })
  
  output$count2 <- renderText({
    paste("Showing top", input$top_n, "movies",
          ifelse(input$genre2 == "All", "(all genres)", paste("in", input$genre2)))
  })
  
  # ---- TAB 3: Budget vs. Success ----
  get_data3 <- reactive({
    df <- movies
    df <- df[!is.na(df$budget) & df$budget > 0, ]
    df <- df[df$release_year >= input$year_range3[1] &
               df$release_year <= input$year_range3[2], ]
    if (input$metric == "revenue") {
      df <- df[!is.na(df$revenue) & df$revenue > 0, ]
    } else {
      df <- df[!is.na(df[[input$metric]]), ]
    }
    if (input$genre3 != "All") {
      df <- df[grepl(input$genre3, df$genres_list, fixed = TRUE), ]
    }
    df
  })
  
  output$scatter <- renderPlotly({
    df <- get_data3()
    y_vals <- df[[input$metric]]
    
    y_label <- switch(input$metric,
                      "revenue"      = "Revenue ($)",
                      "IMDB_Rating"  = "IMDb Rating",
                      "vote_average" = "TMDB Rating",
                      "Meta_score"   = "Metascore")
    
    x_type <- if (input$scale == "Log") "log" else "linear"
    y_type <- if (input$scale == "Log" & input$metric == "revenue") "log" else "linear"
    
    hover <- paste(df$title,
                   "\nBudget: $", format(df$budget, big.mark = ","),
                   "\n", y_label, ":", round(y_vals, 1),
                   "\nDirector:", df$Director)
    
    df_all <- df
    df_all$decade <- "All"
    df_combined <- bind_rows(df_all, df)
    df_combined$decade <- factor(df_combined$decade,
                                 levels = c("All", sort(unique(df$decade))))
    
    y_all <- df_combined[[input$metric]]
    hover_all <- paste(df_combined$title,
                       "\nBudget: $", format(df_combined$budget, big.mark = ","),
                       "\n", y_label, ":", round(y_all, 1),
                       "\nDirector:", df_combined$Director)
    
    # match colors to the uniform palette
    used_genres <- unique(df_combined$primary_genre)
    colors_used <- genre_colors[used_genres]
    
    if (input$genre3 == "All") {
      plot_ly(data = df_combined, x = ~budget, y = y_all,
              color = ~primary_genre, colors = colors_used,
              frame = ~decade,
              text = hover_all, hoverinfo = "text",
              type = "scatter", mode = "markers",
              marker = list(opacity = 0.6, size = 7)) %>%
        layout(xaxis = list(title = "Budget ($)", type = x_type),
               yaxis = list(title = y_label, type = y_type),
               legend = list(title = list(text = "Genre"),
                             orientation = "v", x = 1.02, y = 1)) %>%
        animation_opts(frame = 1000, transition = 500) %>%
        animation_slider(currentvalue = list(prefix = "Decade: ")) %>%
        animation_button(label = "Play")
    } else {
      plot_ly(data = df_combined, x = ~budget, y = y_all,
              frame = ~decade,
              text = hover_all, hoverinfo = "text",
              type = "scatter", mode = "markers",
              marker = list(opacity = 0.6, size = 7, color = "#3498DB")) %>%
        layout(xaxis = list(title = "Budget ($)", type = x_type),
               yaxis = list(title = y_label, type = y_type)) %>%
        animation_opts(frame = 1000, transition = 500) %>%
        animation_slider(currentvalue = list(prefix = "Decade: ")) %>%
        animation_button(label = "Play")
    }
  })
  
  output$count3 <- renderText({
    paste("Showing", nrow(get_data3()), "movies")
  })
  
  # ---- TAB 4: Audience vs. Critics ----
  get_data4 <- reactive({
    df <- movies
    df <- df[!is.na(df$Meta_score), ]
    if (input$rating_source == "IMDB_Rating") {
      df <- df[!is.na(df$IMDB_Rating), ]
    } else {
      df <- df[!is.na(df$vote_average), ]
    }
    df <- df[df$release_year >= input$year_range4[1] &
               df$release_year <= input$year_range4[2], ]
    df
  })
  
  output$bars <- renderPlotly({
    df <- get_data4()
    
    if (input$rating_source == "IMDB_Rating") {
      by_decade <- df %>%
        group_by(primary_genre, decade) %>%
        summarise(audience = mean(IMDB_Rating, na.rm = TRUE),
                  critic = mean(Meta_score, na.rm = TRUE) / 10,
                  n = n(), .groups = "drop")
      by_all <- df %>%
        group_by(primary_genre) %>%
        summarise(audience = mean(IMDB_Rating, na.rm = TRUE),
                  critic = mean(Meta_score, na.rm = TRUE) / 10,
                  n = n(), .groups = "drop") %>%
        mutate(decade = "All")
      aud_label <- "Avg IMDb Rating"
    } else {
      by_decade <- df %>%
        group_by(primary_genre, decade) %>%
        summarise(audience = mean(vote_average, na.rm = TRUE),
                  critic = mean(Meta_score, na.rm = TRUE) / 10,
                  n = n(), .groups = "drop")
      by_all <- df %>%
        group_by(primary_genre) %>%
        summarise(audience = mean(vote_average, na.rm = TRUE),
                  critic = mean(Meta_score, na.rm = TRUE) / 10,
                  n = n(), .groups = "drop") %>%
        mutate(decade = "All")
      aud_label <- "Avg TMDB Rating"
    }
    
    genre_data <- bind_rows(by_all, by_decade)
    genre_data$decade <- factor(genre_data$decade,
                                levels = c("All", sort(unique(by_decade$decade))))
    
    if (input$sort_by == "audience") {
      sort_order <- by_all %>% arrange(desc(audience)) %>% pull(primary_genre)
    } else if (input$sort_by == "critic") {
      sort_order <- by_all %>% arrange(desc(critic)) %>% pull(primary_genre)
    } else {
      sort_order <- by_all %>% mutate(gap = abs(audience - critic)) %>%
        arrange(desc(gap)) %>% pull(primary_genre)
    }
    
    long <- genre_data %>%
      pivot_longer(cols = c(audience, critic),
                   names_to = "type", values_to = "rating") %>%
      mutate(type = ifelse(type == "audience", aud_label,
                           "Avg Metascore (scaled 1-10)"))
    
    plot_ly(data = long, x = ~primary_genre, y = ~rating,
            color = ~type, frame = ~decade, type = "bar",
            text = ~paste("Movies:", n), hoverinfo = "text+y",
            colors = c("#3498DB", "#E74C3C")) %>%
      layout(barmode = "group",
             xaxis = list(title = "Genre", categoryorder = "array",
                          categoryarray = sort_order),
             yaxis = list(title = "Average Rating (1-10)", range = c(0, 10)),
             legend = list(orientation = "h", y = 1.05, x = 0.5,
                           xanchor = "center"),
             margin = list(b = 120)) %>%
      animation_opts(frame = 1000, transition = 500, redraw = TRUE) %>%
      animation_slider(currentvalue = list(prefix = "Decade: ")) %>%
      animation_button(label = "Play")
  })
  
  output$count4 <- renderText({
    paste("Showing", nrow(get_data4()), "movies with both audience and critic ratings")
  })
}

shinyApp(ui, server)